### PR TITLE
Convert logo font to outline

### PR DESCRIPTION
**Pull request by david-bergstrom**
The logo uses a non standard font which renders diffently on different
devices. Convert the font to outline which allows for the logo to
rendered equally on all devices.

### CODE REVIEW

**Comment by drathier** [comment]
wait, why don't we just include the font on the site? How big is the difference? Do all devices have outline installed?

**Comment by drathier** [comment]
oh, sorry. Outline = save as shapes, rather than font? That's great!

**Comment by holmgr** [comment]
That was also my first idea, but including the font would mean an additional request before render and increase loading time. Therefor i chose to accept this solution instead

**Comment by drathier** [comment]
This one is better, as it is way more portable :) Assuming the client can handle svg1.1.

**Pull request merged**
